version: '3.9'
services:
  db:
    image: postgres:14
    container_name: nimbus-db
    environment:
      POSTGRES_PASSWORD: baha123
      POSTGRES_USER: postgres
      POSTGRES_DB: nimbus
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d nimbus"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7
    container_name: nimbus-redis
    ports: ["6379:6379"]
